// ==========================================================
// ぷにコード - ステージデータ (3レベル × 5ステージ = 全15構成)
// 難易度・最大ブロック数・星評価 最適化版
// ==========================================================

export const STAGES = [
  // ── レベル 1：はじめての ぷにコード ──
  {
    id: '1-1',
    name: 'まっすぐ すすおう',
    world: 1,
    gridSize: 3,
    grid: [['.', '.', 'F'], ['.', '.', '.'], ['.', '.', 'T']],
    start: { x: 0, y: 1, dir: 'right' },
    goal: { x: 2, y: 1 },
    blocks: ['forward'],
    maxBlocks: 8,
    stars3: 2,
    stars2: 4,
    hint: '「まえにすすむ」を 2こ ならべて、ほしまで いこう！',
  },
  {
    id: '1-2',
    name: 'もっと すすおう',
    world: 1,
    gridSize: 4,
    grid: [['F', 'W', 'W', 'W'], ['.', '.', '.', '.'], ['W', 'W', 'W', 'W'], ['.', '.', '.', 'T']],
    start: { x: 0, y: 1, dir: 'right' },
    goal: { x: 3, y: 1 },
    blocks: ['forward'],
    maxBlocks: 8,
    stars3: 3,
    stars2: 5,
    hint: 'こんどは すこし とおいよ。3かい すすんでみよう！',
  },
  {
    id: '1-3',
    name: 'ながい みち',
    world: 1,
    gridSize: 5,
    grid: [['.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.']],
    start: { x: 0, y: 2, dir: 'right' },
    goal: { x: 4, y: 2 },
    blocks: ['forward'],
    maxBlocks: 10,
    stars3: 4,
    stars2: 6,
    hint: 'すごく ながいよ！ブロックを たくさん つなげてね。',
  },
  {
    id: '1-4',
    name: 'カギがたの みち',
    world: 1,
    gridSize: 3,
    grid: [['.', '.', 'F'], ['.', 'W', 'W'], ['.', '.', 'T']],
    start: { x: 0, y: 0, dir: 'right' },
    goal: { x: 0, y: 2 },
    blocks: ['forward', 'right'],
    maxBlocks: 10,
    stars3: 4,
    stars2: 6,
    hint: '「みぎにまわる」を つかって、したを むいてから すすおう！',
  },
  {
    id: '1-5',
    name: 'はじめての Lじ',
    world: 1,
    gridSize: 4,
    grid: [['.', '.', '.', 'W'], ['W', 'W', '.', 'W'], ['W', 'W', '.', '.'], ['T', 'W', '.', 'W']],
    start: { x: 0, y: 0, dir: 'right' },
    goal: { x: 2, y: 3 },
    blocks: ['forward', 'right', 'left'],
    maxBlocks: 12,
    stars3: 6,
    stars2: 9,
    hint: 'まがった さきにも 道がつづいているよ。',
  },

  // ── レベル 2：たんけん！迷路 ──
  {
    id: '2-1',
    name: 'ジグザグさんぽ',
    world: 2,
    gridSize: 4,
    grid: [['.', '.', '.', '.'], ['.', '.', '.', 'W'], ['W', '.', '.', '.'], ['W', 'W', 'W', 'T']],
    start: { x: 0, y: 0, dir: 'right' },
    goal: { x: 2, y: 2 },
    blocks: ['forward', 'right', 'left'],
    maxBlocks: 12,
    stars3: 6,
    stars2: 9,
    hint: 'みぎ、ひだり、どっちに まがるか よくかんがえてね。',
  },
  {
    id: '2-2',
    name: 'Sじの おとずれ',
    world: 2,
    gridSize: 5,
    grid: [['.', '.', '.', 'W', 'F'], ['W', 'W', '.', 'W', 'W'], ['.', '.', '.', '.', '.'], ['W', 'W', '.', 'W', 'W'], ['T', '.', '.', '.', '.']],
    start: { x: 0, y: 0, dir: 'right' },
    goal: { x: 0, y: 4 },
    blocks: ['forward', 'right', 'left'],
    maxBlocks: 12,
    stars3: 8,
    stars2: 12,
    hint: 'Sの かたちに あるいてみよう！',
  },
  {
    id: '2-3',
    name: 'もりの めいろ',
    world: 2,
    gridSize: 5,
    grid: [['.', '.', 'W', '.', 'F'], ['.', 'W', 'W', '.', 'W'], ['.', '.', '.', '.', '.'], ['W', 'W', '.', 'W', 'W'], ['T', '.', '.', '.', '.']],
    start: { x: 0, y: 0, dir: 'down' },
    goal: { x: 4, y: 4 },
    blocks: ['forward', 'right', 'left'],
    maxBlocks: 15,
    stars3: 10,
    stars2: 15,
    hint: '木（木）に ぶつからないように、とおまわりしよう。',
  },
  {
    id: '2-4',
    name: 'いりくんだ みち',
    world: 2,
    gridSize: 5,
    grid: [['.', 'W', '.', '.', '.'], ['.', 'W', '.', 'W', '.'], ['.', '.', '.', 'W', '.'], ['W', 'W', '.', '.', '.'], ['T', 'W', 'W', 'W', '.']],
    start: { x: 0, y: 0, dir: 'down' },
    goal: { x: 4, y: 4 },
    blocks: ['forward', 'right', 'left'],
    maxBlocks: 15,
    stars3: 10,
    stars2: 15,
    hint: 'ちょっと むずかしい めいろだ。がんばって！',
  },
  {
    id: '2-5',
    name: 'ぐるっと ひとまわり',
    world: 2,
    gridSize: 5,
    grid: [['.', '.', '.', '.', '.'], ['.', 'W', 'W', 'W', '.'], ['.', 'W', 'T', 'W', '.'], ['.', 'W', '.', 'W', '.'], ['.', '.', '.', 'W', 'F']],
    start: { x: 0, y: 4, dir: 'up' },
    goal: { x: 2, y: 3 },
    blocks: ['forward', 'right', 'left'],
    maxBlocks: 15,
    stars3: 8,
    stars2: 12,
    hint: '大きく まわって、まんなかの ほしを めざそう。',
  },

  // ── レベル 3：まほうの くりかえし ──
  {
    id: '3-1',
    name: 'らくらく ステップ',
    world: 3,
    gridSize: 5,
    grid: [['.', '.', '.', '.', 'F'], ['W', 'W', 'W', 'W', '.'], ['.', '.', '.', '.', '.'], ['W', 'W', 'W', 'W', '.'], ['T', '.', '.', '.', '.']],
    start: { x: 4, y: 0, dir: 'down' },
    goal: { x: 0, y: 4 },
    blocks: ['forward', 'repeat2', 'repeat3', 'repeat4', 'right', 'left'],
    maxBlocks: 15,
    stars3: 4,
    stars2: 6,
    hint: '「4かいくりかえす」を つかうと、いっきに すすめるよ！',
  },
  {
    id: '3-2',
    name: 'くりかえし ターン',
    world: 3,
    gridSize: 5,
    grid: [['.', '.', '.', '.', '.'], ['.', 'W', 'W', 'W', '.'], ['.', 'W', '.', 'W', '.'], ['.', 'W', 'T', 'W', '.'], ['.', '.', '.', '.', '.']],
    start: { x: 0, y: 0, dir: 'right' },
    goal: { x: 2, y: 3 },
    blocks: ['forward', 'repeat2', 'repeat3', 'right', 'left'],
    maxBlocks: 15,
    stars3: 6,
    stars2: 9,
    hint: 'くりかえしを つかうと、コードが すっきりするよ。',
  },
  {
    id: '3-3',
    name: 'しかくの パターン',
    world: 3,
    gridSize: 5,
    grid: [['.', '.', '.', '.', '.'], ['.', 'F', '.', '.', '.'], ['.', '.', '.', 'W', '.'], ['.', '.', '.', '.', '.'], ['T', '.', '.', '.', '.']],
    start: { x: 1, y: 1, dir: 'right' },
    goal: { x: 0, y: 4 },
    blocks: ['forward', 'repeat2', 'repeat3', 'right', 'left'],
    maxBlocks: 15,
    stars3: 6,
    stars2: 10,
    hint: '同じ うごきが あるときは「くりかえし」を おもいだして！',
  },
  {
    id: '3-4',
    name: 'かいだんを のぼろう',
    world: 3,
    gridSize: 6,
    grid: [['.', '.', '.', '.', '.', 'F'], ['.', '.', '.', '.', 'W', '.'], ['.', '.', '.', 'W', '.', '.'], ['.', '.', 'W', '.', '.', '.'], ['.', 'W', '.', '.', '.', '.'], ['T', '.', '.', '.', '.', '.']],
    start: { x: 5, y: 5, dir: 'left' },
    goal: { x: 0, y: 0 },
    blocks: ['forward', 'repeat2', 'repeat3', 'right', 'left'],
    maxBlocks: 20,
    stars3: 6,
    stars2: 10,
    hint: 'いって、まがって、いって、まがって…。ループの 出番だ！',
  },
  {
    id: '3-5',
    name: 'さいごの だいぼうけん',
    world: 3,
    gridSize: 6,
    grid: [['.', '.', '.', '.', '.', 'F'], ['W', 'W', 'W', 'W', '.', '.'], ['.', '.', '.', '.', '.', '.'], ['.', 'W', 'W', 'W', 'W', 'W'], ['.', '.', '.', '.', '.', 'T'], ['W', 'W', 'W', 'W', '.', '.']],
    start: { x: 5, y: 0, dir: 'down' },
    goal: { x: 4, y: 5 },
    blocks: ['forward', 'repeat2', 'repeat3', 'repeat4', 'right', 'left'],
    maxBlocks: 20,
    stars3: 8,
    stars2: 12,
    hint: 'これまでの ぜんぶを つかって、ゴールを めざせ！マスターだ！',
  },
];

// 共通設定
export const BLOCK_DEFS = {
  forward: { id: 'forward', label: 'まえにすすむ', icon: '🐾', cssClass: 'forward' },
  right: { id: 'right', label: 'みぎにまわる', icon: '↻', cssClass: 'turn-right' },
  left: { id: 'left', label: 'ひだりにまわる', icon: '↺', cssClass: 'turn-left' },
  repeat2: { id: 'repeat2', label: '2かいくりかえす', icon: '🔁2', cssClass: 'repeat' },
  repeat3: { id: 'repeat3', label: '3かいくりかえす', icon: '🔁3', cssClass: 'repeat' },
  repeat4: { id: 'repeat4', label: '4かいくりかえす', icon: '🔁4', cssClass: 'repeat' },
};

export const DIRECTIONS = {
  up: { dx: 0, dy: -1, angle: 0 },
  right: { dx: 1, dy: 0, angle: 90 },
  down: { dx: 0, dy: 1, angle: 180 },
  left: { dx: -1, dy: 0, angle: 270 },
};

export function turnRight(dir) {
  const order = ['up', 'right', 'down', 'left'];
  return order[(order.indexOf(dir) + 1) % 4];
}

export function turnLeft(dir) {
  const order = ['up', 'right', 'down', 'left'];
  return order[(order.indexOf(dir) + 3) % 4];
}
